from __future__ import annotations

from enum import Enum


class ProjectStatus(str, Enum):
    INIT = "INIT"
    DESIGN_READY = "DESIGN_READY"
    BOOTSTRAP_RUNNING = "BOOTSTRAP_RUNNING"
    BOOTSTRAP_REVIEW_PENDING = "BOOTSTRAP_REVIEW_PENDING"
    BOOTSTRAP_READY = "BOOTSTRAP_READY"
    PHASE_ACTIVE = "PHASE_ACTIVE"
    PHASE_DONE = "PHASE_DONE"
    RELEASE_READY = "RELEASE_READY"
    CLOSED = "CLOSED"
    BLOCKED_ON_HUMAN = "BLOCKED_ON_HUMAN"
    BLOCKED_ON_OPEN_BLOCKERS = "BLOCKED_ON_OPEN_BLOCKERS"
    BLOCKED_ON_MISSING_ARTIFACT = "BLOCKED_ON_MISSING_ARTIFACT"
    BLOCKED_ON_WORKER_FAILURE = "BLOCKED_ON_WORKER_FAILURE"


class PhaseStatus(str, Enum):
    NOT_STARTED = "NOT_STARTED"
    CONTRACT_VALIDATED = "CONTRACT_VALIDATED"
    CONTRACT_APPROVED = "CONTRACT_APPROVED"
    BUILDING = "BUILDING"
    REVIEW_PENDING = "REVIEW_PENDING"
    BLOCKER_FIXING = "BLOCKER_FIXING"
    RECHECK_PENDING = "RECHECK_PENDING"
    READY_TO_CLOSE = "READY_TO_CLOSE"
    DONE = "DONE"
    BLOCKED_ON_HUMAN = "BLOCKED_ON_HUMAN"
    BLOCKED_ON_OPEN_BLOCKERS = "BLOCKED_ON_OPEN_BLOCKERS"
    BLOCKED_ON_MISSING_ARTIFACT = "BLOCKED_ON_MISSING_ARTIFACT"
    BLOCKED_ON_WORKER_FAILURE = "BLOCKED_ON_WORKER_FAILURE"


class JobStatus(str, Enum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    DONE_WITH_CONCERNS = "DONE_WITH_CONCERNS"
    FAILED = "FAILED"
    CANCELED = "CANCELED"


class GateDecisionType(str, Enum):
    PASS = "PASS"
    CONDITIONAL_PASS = "CONDITIONAL_PASS"
    FAIL = "FAIL"
    INVALID_FORMAT = "INVALID_FORMAT"


class ReviewOriginStage(str, Enum):
    PHASE_REVIEW = "PHASE_REVIEW"
    PHASE_RECHECK = "PHASE_RECHECK"
    BOOTSTRAP_REVIEW = "BOOTSTRAP_REVIEW"


class BootstrapResumeStage(str, Enum):
    BOOTSTRAP_REPO = "BOOTSTRAP_REPO"
    BOOTSTRAP_REVIEW = "BOOTSTRAP_REVIEW"


class PhaseResumeStage(str, Enum):
    BUILD = "BUILD"
    REVIEW = "REVIEW"
    FIX_BLOCKERS = "FIX_BLOCKERS"
    RECHECK = "RECHECK"
    APPEND_BACKLOG = "APPEND_BACKLOG"
    CLOSE_PHASE = "CLOSE_PHASE"


class ApprovalType(str, Enum):
    CONTRACT_APPROVAL = "CONTRACT_APPROVAL"
    SCOPE_CHANGE = "SCOPE_CHANGE"
    CLOSE_PHASE_WITH_IMPORTANT_OPEN = "CLOSE_PHASE_WITH_IMPORTANT_OPEN"
    BOOTSTRAP_READY_WITH_IMPORTANT_OPEN = "BOOTSTRAP_READY_WITH_IMPORTANT_OPEN"
    RELEASE_READY_CONFIRM = "RELEASE_READY_CONFIRM"


class ApprovalStatus(str, Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
